### ISSUE TITLE
Error: Namespace='com.SampleMapper2' not found.

### ISSUE THREAD

**Issue by atsu85** [harawata/mybatipse#26]
Validation error is added to Problems view when I reference one mapper from another mapper.

For example, when i have SampleMapper1 and SampleMapper2, and SampleMapper1 contains smth like:

	<resultMap id="mapper1ResultMap" type="com.SomeClass">
		<association property="someField" resultMap="com.SampleMapper2.mapper2ResultMap" />
	</resultMap>

or

	<sql id="mapper1Sql">
		<include refid="com.SampleMapper2.mapper2fragment" />
	</sql>

Currently my problems view is polluted by this type of false alarm errors - would be nice to see it fixed :)

**Comment by harawata** [comment]
Hi!

It works for me without an error.

Please make sure that your XML mappers are located in __Source Folders__ (the folders with a package mark on their icon).
You might have to clean the project after adding a source folder.

**Comment by atsu85** [comment]
Hi, by looking at the source code i came to the same conclusion (that mappers need to be in a source folder) based on this line:
https://github.com/harawata/mybatipse/blob/master/mybatipse/src/net/harawata/mybatipse/mybatis/MapperNamespaceCache.java#L122

So adding mappers folder to the java build path fixed the problem.

Probably https://github.com/harawata/mybatipse#configuration section should be improved, so it would mention that mappers need to be in java build path - so I'd leave this issue opened until documentation is updated.

**Comment by harawata** [comment]
Hi, I'm sorry for a late reply.
I have just updated the Configuration section as you suggested.
Thank you for the feedback!
