### ISSUE TITLE
Which eclipse formatter settings to use when contributing code?

### ISSUE THREAD

**Issue by atsu85** [harawata/mybatipse#27]
Hello,
I'd like to contribute code to this project, but it looks like non of the eclipse built-in java code formatters is used in this project.

Could You export eclipse java code formatter that should be used for this project and maybe include it in the project source code or upload it somewhere?

Best Regards,
Ats

**Comment by harawata** [comment]
Hi Ats,

Thanks for the offer!
I've never expected code contribution on this project, but I'll make the current formatter available in some form as soon as possible.

Regards,
Iwao
