### ISSUE TITLE
XmlValidator adds markers but not add it to ValidationResult

### ISSUE THREAD

**Issue by vazul** [harawata/mybatipse#31]
Hi Iwao!

Just realized, that when I validate my mappers, it won't report any error, however, markers will be set. It is commented out, but don't know the reason:

https://github.com/harawata/mybatipse/blob/master/mybatipse/src/net/harawata/mybatipse/mybatis/XmlValidator.java#L433

It is necessary to do so? If I uncomment it, it will add the same marker (as I can see), and the error will be counted in the XML ValidationResult also.

Best regards,

-- Vazul

**Comment by harawata** [comment]
Thank you for the feedback László!

If I, for example, specify an incorrect property name, a marker is set on the line and the error is reported in the Problem View.

![mybatipse 31](https://cloud.githubusercontent.com/assets/149268/6363841/92b60820-bce1-11e4-99f3-c4720d9f7dd5.png)

If the error is not shown in the Problem View, please check the contents configuration of the Problem View and make sure 'MyBatis XML Problem' is selected.
Or did you mean something different by 'it won't report any error' ?

Reading [the doc](http://help.eclipse.org/indigo/index.jsp?topic=%2Forg.eclipse.wst.validation.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fwst%2Fvalidation%2FValidatorMessage.html), using ValidatorMessage/ValidationResult should not affect the visibility of the problem.

Regards,
Iwao

**Comment by vazul** [comment]
Hi Iwao!

Thanks for the response.

What I have noticed, that when you do manual validation on the mapper xml file, the validation will result in no error, however, MyBatis problem markers will be set. I think that's because the validation message is not added to the validation result. I think, it should be better to use the ValidationResult.
Maybe you choose to handle your own markers, because you call XmlValidator directly from MybatipseIncrementalBuilder. Maybe, ValidationFramework.getDefault().validate(..) can be used, which will set markers based on ValidationResult.

And Validation Builder also doing so, and we have Validation Builder set on our projects (if you enable faceted project for a project with Utility Project facet, it will automatically set Validation Builder on that project).(another problem is in this case that mapper xml files in output directory will be validated also)

As I can understand, MybatipseIncrementalBuilder is used to validate mapper xml files, when corresponding java files have been changed. But looking at the code, it will validate all mappers in every case, no matter what is changed. But there is a MybatipseResourceChangeListener, where you track java file changes. Here, the corresponding mapper xml can be found in MapperNamespaceCache, and maybe the mapper can be revalidated, in case when Validation Builder is also set up.

Sorry for this long brainstorming, just wanted to clarify what happens under the hood, and what I think that should be good in conjunction with Validation Builder, manual validation and regarding revalidatiing mapper xml files upon corresponding mapper interface change.

**Comment by harawata** [comment]
> What I have noticed, that when you do manual validation on the mapper xml file, the validation will result in no error, however, MyBatis problem markers will be set.

I still cannot reproduce (or do not understand) your problem.
By 'manual validation', you mean 'right clicking the XML mapper file and choose __Validate__ from the contextual menu', is that correct? 
On my environment, the error is reported in my Problem View as seen in the picture in my previous comment.

I appreciate your suggestions, but I need to reproduce the problem before modifying the code.
Please provide the exact steps to reproduce the problem, preferably on a clean workspace.

Oh, and have you enabled the __MyBatipse Nature__ as explained in the [README](https://github.com/harawata/mybatipse#mybatis-nature) ?

> As I can understand, MybatipseIncrementalBuilder is used to validate mapper xml files, when corresponding java files have been changed. But looking at the code, it will validate all mappers in every case, no matter what is changed. But there is a MybatipseResourceChangeListener, where you track java file changes. Here, the corresponding mapper xml can be found in MapperNamespaceCache, and maybe the mapper can be revalidated, in case when Validation Builder is also set up.

Let me try to explain the difficulty.
For example, when a domain class is changed, all the XML mappers referencing this domain object (or its subclasses) must be re-validated and I couldn't find a reasonable way to search those _corresponding_ mappers.
This is why MyBatipse validates all the XML mappers on each change.

**Comment by vazul** [comment]
Hi Iwao!

Yes, manual validation is by right click and Validate. In my environment, the result will be displayed in a dialog box, and this dialog box will show no error, however, error markers are set. Not a big issue, just made me a little confused.

Regarding the revalidation upon build event: I see now. The can be any change, not just in the mapper interface itself, but in the return types and method argument types as well, so yes, if you don't maintain a correct full map of java to mapper xml references, then this will work.

Thanks for the answers, best regards,

-- Vazul

**Comment by harawata** [comment]
Oh...the dialog!
I didn't pay any attention to the dialog contents, sorry XD
I'll follow your suggestion and see if it solves the problem.
Thank you very much for the explanation!

Regards,
Iwao

**Comment by harawata** [comment]
I have released 1.0.12 which should fix the result dialog issue.
Thanks again for your report!
