### ISSUE TITLE
Type aliases are not correctly detected when package is specified in the config

### ISSUE THREAD

**Issue by harawata** [harawata/mybatipse#42]
With config like below, MyBatipse only detects the direct children of the specified packages.

```xml
<!-- mybatis config -->
<typeAliases>
  <package name="pkg1" />
</typeAliases>
```
```xml
<!-- spring config -->
<bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
  <property name="typeAliasesPackage" value="pkg1"/>
  ...
</bean>
```

Reported by @akacd in [this comment](https://github.com/harawata/mybatipse/issues/15#issuecomment-204879345)

**Comment by harawata** [comment]
@akacd
Please let me know if your problem is not resolved with 1.0.16.
Thank you again!

**Comment by akacd** [comment]
@harawata 
I tried with 1.0.16 in several ways,but it seems there are still errors like this "Class/TypeAlias 'Article' not found."

original code:
`  <property name="typeAliasesPackage" value="com.thinkgem.jeesite"/>`
   

then I add all the packages,then validate the resources/mapping dir,there are still errors -->  
  		`<property name="typeAliasesPackage" value="com.thinkgem.jeesite.modules.act.entity,com.thinkgem.jeesite.modules.cms.entity,com.thinkgem.jeesite.modules.gen.entity,com.thinkgem.jeesite.modules.oa.entity,com.thinkgem.jeesite.modules.sys.entity,com.thinkgem.jeesite.modules.test.entity"/>`

then I add a single package for testing, but again errors.
 		`<property name="typeAliasesPackage" value="com.thinkgem.jeesite.modules.cms.entity"/>
        `
the entities' dirs are like this:
![image](https://cloud.githubusercontent.com/assets/6822570/14232287/5bbdce18-f9d8-11e5-9533-683aca0b7e30.png)

**Comment by akacd** [comment]
@harawata  
And I just  uninstall the mybatipse.Leaving only the 
`<property name="typeAliasesPackage" value="com.thinkgem.jeesite.modules.cms.entity"/> `
then validate all the resources/mapping dirs ,no errors at all.
Of course it shows errors in console when I tried to start the project.

I don't know if my configurations are wrong?I'm using 
Spring Tool Suite 
Version: 3.7.3.RELEASE
Build Id: 201602250940
Platform: Eclipse Mars.2 (4.5.2)

**Comment by akacd** [comment]
I also trie the project:
[https://github.com/mybatis/jpetstore-6](url)

The same errors : "Class/TypeAlias 'Account' not found.".
The configuration is below ,the project has all the entities in the package: org.mybatis.jpetstore.domain
`  
<bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
        <property name="dataSource" ref="dataSource" />
        <property name="typeAliasesPackage" value="org.mybatis.jpetstore.domain" />
    </bean>
`

**Comment by harawata** [comment]
There seems to be some incompatibility with Spring Tool Suite.
Sunday is over, so please give me a few days to fix it.
Thank you for the helpful information and sorry for the inconvenience!

**Comment by DoneSpeak** [comment]
Have this bug been fixed? It happens again.

Mybatipse: 1.2.1
Eclipse: Neon.3 Release (4.6.3)
Spring: 4.1.3.RELEASE
Maven: 3.5.0

and I use SpringMVC instead of SpringBoot.

**Comment by harawata** [comment]
@DoneSpeak ,

Have you read the [doc](https://github.com/mybatis/mybatipse#type-alias) ?
If it didn't resolve the problem, please create a new issue with the details about your project, notably how you configure type aliases.

**Comment by DoneSpeak** [comment]
@harawata ,  
Oh, I'm sorry. I will read the doc again more carefully and try it again.  
Thanks, sincerely.
